### ISSUE TITLE
Too many open files (os error 24)

### ISSUE THREAD

**Issue by vilesovds** [KaranGauswami/socks-to-http-proxy#14]
After few hours of work got error Too many open files (os error 24)

**Comment by KaranGauswami** [comment]
@vilesovds ,

You will need to increase ulimit in system. 

https://stackoverflow.com/questions/68656329/multiprocessing-causing-oserror-errno-24-too-many-open-files-error

**Comment by KaranGauswami** [comment]
Closing this issue for now, If problem is not resolved . Feel free to open it again.
