### ISSUE TITLE
Something is wrong with cargo.lock

### ISSUE THREAD

**Issue by uaquax** [KaranGauswami/socks-to-http-proxy#15]
Something is definitely wrong with cargo.lock, because I tried to copy the entire file, with cargo.toml, but until I copied cago.lock I was getting lots of compiler errors. Maybe some dependencies are deprecated or Idk, but that's strange.

**Comment by KaranGauswami** [comment]
Thanks for Report @uaquax ,

It might be during underlying hyper library that is currently in rc state, It should work now.

**Comment by uaquax** [comment]
Yeah thanks
