### ISSUE TITLE
SOCKS5

### ISSUE THREAD

**Issue by alamia442** [KaranGauswami/socks-to-http-proxy#2]
not support socks5 with user & pass?

**Comment by KaranGauswami** [comment]
@alamia442 currently it is not supported 

Currently I am having trouble implementing proper api but you can change method here in [this line](https://github.com/KaranGauswami/socks-to-http-proxy/blob/3fa2bef8e3c520f6a25e5383bea8d02a37cce9a7/src/main.rs#L67)

Replacing this line 
```rs
let mut stream = Socks5Stream::connect(socks_address, plain).await?;
```
with
```rs
let mut stream = Socks5Stream::connect_with_password(socks_address, plain,"username","password").await?;
```

**Comment by KaranGauswami** [comment]
@alamia442 Authentication added in v0.3.0
