### ISSUE TITLE
invalid socket address syntax

### ISSUE THREAD

**Issue by Coquelicots** [KaranGauswami/socks-to-http-proxy#24]
Hello,

I'm getting this error when trying to connect via a ipvanish proxy.

error: invalid value 'ams.socks.ipvanish.com:1080' for '--socks-address <SOCKS_ADDRESS>': invalid socket address syntax

**Comment by KaranGauswami** [comment]
Hi @Coquelicots 

I think i have not added support for DNS resolution. Please try to use IP instead .

I will try to add DNS resolution soon enough.

**Comment by Coquelicots** [comment]
Okay, thank you very much for your help. 👍
